[package]
name = "frutti-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
tutti-frutti = { path = "../tutti-frutti" }
tokio = { version = "1.0", features = ["full"] }
ratatui = "0.26.1"
crossterm = "0.27.0"
anyhow = "1.0"
